# Generated by Django 5.2 on 2025-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('press', 'Пресс-секретарь'), ('commander', 'Командир')], max_length=10, null=True, verbose_name='Роль'),
        ),
    ]
