# Generated by Django 5.2 on 2025-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vk_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на VK'),
        ),
    ]
