# Generated by Django 5.2 on 2025-05-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_customuser_vk_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mysite.newspost')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
